/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CareRouteImport } from './routes/care'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCategoryRouteImport } from './routes/shop/$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/journal': typeof JournalIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track'
    | '/wishlist'
    | '/journal/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$category'
    | '/journal/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track'
    | '/wishlist'
    | '/journal/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$category'
    | '/journal'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/privacy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/track'
    | '/wishlist'
    | '/journal/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/shop/$category'
    | '/journal/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CareRoute: typeof CareRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
  JournalSlugRoute: typeof JournalSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CareRoute: CareRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
  JournalSlugRoute: JournalSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  JournalIndexRoute: JournalIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
